version: '2'

services:
  postgres:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  app:
    container_name: streamr
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: rails s
    volumes:
      - '.:/app'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq -e production -C config/sidekiq_schedule.yml
    volumes:
      - '.:/app'

  cable:
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80


volumes:
  redis:
  postgres:
